config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions' }
  devise_scope :user do
    match '/users/auth/saml', to: 'users/omniauth_callbacks#passthru', as: :user_omniauth_authorize, via: [:get, :post]
    match '/users/auth/saml/callback', to: 'users/omniauth_callbacks#saml', as: "user_omniauth_callback_saml".to_sym, via: [:get, :post]
    get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
    get 'users/unauthorized', to: 'users/sessions#unauthorized', as: :unauthorized_user
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      constraints(prefix: /[^\/]+/) do # Allow prefixes to contain "."
        get 'handles/:prefix/:suffix' => 'handles#show', as: :handle
        patch 'handles/:prefix/:suffix' => 'handles#update', as: :update_handle
        post 'handles' => 'handles#create', as: :new_handle
        get 'handles/exists' => 'handles#exists', as: :handle_exists
        get 'handles/info' => 'handles#info', as: :handle_info
      end
    end
  end

  resources :handles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'

  get '/ping' => 'ping#verify'
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @q = Handle.ransack(params[:q])
  end
end

app/views/home/index.html.erb
<h1>UMD Handle Service</h1>

<div id="home-jumbo" class='jumbotron'>
  <div class="row">
  <%= search_form_for @q do |f| %>
    <div class="form-inline text-center">
      <%= f.label :handle_cont, 'Handle' %>
      <%= f.search_field :handle_cont, {placeholder: 'e.g. 1903.1/22', class:'form-control'} %>
      <%= f.submit url: handles_url, class: 'btn btn-default'  %>
    </div>
  <% end %>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Other Services</h3>
  </div>
  <div class="panel-body">
    <%= link_to 'Handles List', handles_path, class: "btn btn-default" %>
  </div>
</div>