config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions' }
  devise_scope :user do
    match '/users/auth/saml', to: 'users/omniauth_callbacks#passthru', as: :user_omniauth_authorize, via: [:get, :post]
    match '/users/auth/saml/callback', to: 'users/omniauth_callbacks#saml', as: "user_omniauth_callback_saml".to_sym, via: [:get, :post]
    get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
    get 'users/unauthorized', to: 'users/sessions#unauthorized', as: :unauthorized_user
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      constraints(prefix: /[^\/]+/) do # Allow prefixes to contain "."
        get 'handles/:prefix/:suffix' => 'handles#show', as: :handle
        patch 'handles/:prefix/:suffix' => 'handles#update', as: :update_handle
        post 'handles' => 'handles#create', as: :new_handle
        get 'handles/exists' => 'handles#exists', as: :handle_exists
        get 'handles/info' => 'handles#info', as: :handle_info
      end
    end
  end

  resources :handles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'

  get '/ping' => 'ping#verify'
end

app/models/handle.rb
# frozen_string_literal: true

# Maps a handle URL to the actual resource URL
class Handle < ApplicationRecord
  around_create :mint_next_suffix, if: -> { suffix.blank? }
  validate :validate_prefix
  validates :suffix, uniqueness: { scope: :prefix }
  validate :validate_repo
  validates :repo_id, presence: { message: 'is required' }
  validate :validate_url

  # Ransack object to allow "handle" (i.e., "<prefix>/<suffix>") searches
  ransacker :handle do |parent|
    Arel::Nodes::InfixOperation.new(
      '||', Arel::Nodes::InfixOperation.new(
              '||', parent.table[:prefix], Arel::Nodes.build_quoted('/')
            ),
      parent.table[:suffix]
    )
  end

  # Lock for ensuring synchronization in mint_next_suffix
  @@semaphore = Mutex.new # rubocop:disable Style/ClassVars

  def validate_prefix
    # Using this method instead of "presence" and "inclusion" validatons
    # so "Handle.prefixes" does not have to be place above validations in the
    # source code.
    errors.add(:prefix, 'is required') and return if prefix.nil?

    errors.add(:prefix, "'#{prefix}' is not a valid prefix") unless Handle.prefixes.include?(prefix)
  end

  def validate_repo
    # Using this method instead of "presence" and "inclusion" validatons
    # so "Handle.prefixes" does not have to be place above validations in the
    # source code.
    errors.add(:repo, 'is required') and return if repo.nil?

    errors.add(:repo, "'#{repo}' is not a valid repository") unless Handle.repos.include?(repo)
  end

  def validate_url
    errors.add(:url, 'is required') and return if url.nil?

    valid = false
    begin
      uri = URI.parse(url)
      valid = uri.is_a?(URI::HTTP) && uri.host.present?
    rescue URI::InvalidURIError
      valid = false
    end

    errors.add(:url, "'#{url}' is not a valid URL") unless valid
  end

  def self.prefixes
    %w[1903.1]
  end

  def self.repos
    %w[aspace avalon fcrepo fedora2]
  end

  def to_handle_string
    "#{prefix}/#{suffix}"
  end

  # Returns the fully-qualified URL to use as the handle URL
  def handle_url
    "#{Rails.application.config.handle_http_proxy_base}#{prefix}/#{suffix}"
  end

  private

    # Mints the next suffix, used with "around_create" callback
    def mint_next_suffix
      # Synchronized to ensure that multiple invocations can't get the
      # suffix number
      @@semaphore.synchronize do
        # Determine the current max value for the suffix, scoped to the prefix
        max_value = Handle.group(:prefix).maximum(:suffix)[prefix]

        # max_value will be nil only if this is the first suffix for a prefix
        max_value = 0 if max_value.nil?

        # Set the suffix value for this instance by incrementing the max_value
        self.suffix = max_value + 1

        # Continue with create
        yield
      end
    end
end

app/controllers/api/v1/handles_controller.rb
# frozen_string_literal: true

module Api
  module V1
    # Handles controller for the REST API
    class HandlesController < Api::ApiController
      respond_to :json

      def show
        @handle = Handle.find_by(suffix: params[:suffix], prefix: params[:prefix])
        render json: {}, status: :not_found if @handle.nil?
      end

      def create
        @handle = Handle.new(handle_params)

        render json: { errors: @handle.errors.full_messages }, status: :bad_request unless @handle.save
      end

      # PATCH /handles/prefix/suffix
      def update
        @handle = Handle.find_by(suffix: params[:suffix], prefix: params[:prefix])
        Rails.logger.info("Updating handle #{@handle}, is nil? #{@handle.nil?}")
        if @handle.nil?
          render json: {}, status: :not_found
        else
          @handle.update(handle_update_params)
          render json: { errors: @handle.errors.full_messages }, status: :bad_request unless @handle.save
        end
      end

      def exists
        @repo = params[:repo]
        @repo_id = params[:repo_id]

        @errors = []
        @errors << '"repo" is required' if @repo.blank?
        @errors << '"repo_id" is required' if @repo_id.blank?
        render json: { errors: @errors },  status: :bad_request and return unless @errors.empty?

        @handle = Handle.find_by repo: @repo, repo_id: @repo_id
        @exists = !@handle.nil?
      end

      def info
        @prefix = params[:prefix]
        @suffix = params[:suffix]

        @errors = []
        @errors << '"prefix" is required' if @prefix.blank?
        @errors << '"suffix" is required' if @suffix.blank?
        render json: { errors: @errors }, status: :bad_request and return unless @errors.empty?

        @handle = Handle.find_by prefix: @prefix, suffix: @suffix
        @exists = !@handle.nil?
      end

      private

        # Only allow a list of trusted parameters through.
        def handle_params
          params.require(:handle).permit(:prefix, :url, :repo, :repo_id, :description, :notes)
        end

        # Only allow a list of trusted parameters through.
        def handle_update_params
          params.require(%i[prefix suffix])
          params.permit(:url, :repo, :repo_id, :description, :notes)
        end
    end
  end
end

app/controllers/handles_controller.rb
# frozen_string_literal: true

class HandlesController < ApplicationController
  before_action :set_handle, only: %i[show edit update destroy]

  # GET /handles or /handles.json
  def index
    @q = Handle.ransack(params[:q])
    @q.sorts = 'updated_at desc' if @q.sorts.empty?
    @handles = @q.result.page(params[:page])

    @expand_sort_form = search_params?
    @show_no_handles_found = @handles.count.zero?
  end

  # Returns true if the request contains non-empty search parameters,
  # false otherwise.
  #
  # Mainly intended for determining whether the search panel should be shown
  # as expanded or collapsed
  def search_params?
    q = params[:q]
    return false if q.nil?

    q.each do |key, value|
      # Skip sort key
      next if key == 's'
      return true if value.present?
    end
    false
  end

  # GET /handles/1 or /handles/1.json
  def show
  end

  # GET /handles/new
  def new
    @handle = Handle.new
  end

  # GET /handles/1/edit
  def edit
  end

  # POST /handles or /handles.json
  def create
    @handle = Handle.new(handle_params)

    respond_to do |format|
      if @handle.save
        format.html { redirect_to @handle, notice: 'Handle was successfully created.' }
        format.json { render :show, status: :created, location: @handle }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @handle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /handles/1 or /handles/1.json
  def update # rubocop:disable Metrics/MethodLength
    respond_to do |format|
      # Don't allow the prefix to be changed via update
      allowed_params = handle_params
      allowed_params.delete(:prefix)

      if @handle.update(allowed_params)
        format.html { redirect_to @handle, notice: 'Handle was successfully updated.' }
        format.json { render :show, status: :ok, location: @handle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @handle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /handles/1 or /handles/1.json
  def destroy
    @handle.destroy
    respond_to do |format|
      format.html { redirect_to handles_url, notice: 'Handle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_handle
      @handle = Handle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def handle_params
      params.require(:handle).permit(:prefix, :url, :repo, :repo_id, :description, :notes)
    end
end

app/helpers/handles_helper.rb
# frozen_string_literal: true

module HandlesHelper
end

app/views/handles/_form.html.erb
<%= form_with(model: handle) do |form| %>
  <%= render 'form_errors', errors: handle.errors %>

  <table class="table table-striped">
    <tbody>
    <tr>
      <%# Only new records should be allowed to set the prefix %>
      <% if handle.new_record? %>
        <th><%= form.label :prefix %></th>
        <td><%= form.select(:prefix, Handle.prefixes) %></td>
      <% else %>
        <th><%= form.label :prefix %></th>
        <td><%= handle.prefix %></td>
      <% end %>
    </tr>

    <% if handle.new_record? %>
      <th><%= form.label :suffix %></th>
      <td>Suffix is generated automatically</td>
    <% else %>
      <tr>
        <th><%= form.label :suffix %></th>
        <td><%= handle.suffix %></td>
      </tr>
    <% end %>

    <tr>
      <th><%= form.label :url %></th>
      <td><%= form.text_field :url, style: "min-width: 100%" %></td>
    </tr>

    <tr>
      <th><%= form.label :repo %></th>
      <td><%= form.select(:repo, Handle.repos) %></td>
    </tr>

    <tr>
      <th><%= form.label :repo_id %></th>
      <td><%= form.text_field :repo_id, style: "min-width: 100%" %></td>
    </tr>

    <tr>
      <th><%= form.label :description %></th>
      <td><%= form.text_field :description, style: "min-width: 100%" %></td>
    </tr>

    <tr>
      <th><%= form.label :notes %></th>
      <td><%= form.text_area :notes, rows: "6", style: "min-width: 100%" %></td>
    </tr>

    <tr>
      <th></th>
      <td>
        <%= form.submit class: 'btn btn-success' %>
        <%= link_to 'Cancel', handle, class: 'btn btn-danger' %>
        <%= link_to 'List All Handles', handles_path, class: 'btn btn-default' %>
      </td>
    </tr>
    </tbody>
  </table>
<% end %>

app/views/handles/_no_handles_found.html.erb
<div class="alert alert-warning" role="alert">
  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
  <span class="sr-only">Note:</span>
  No handles found!
</div>

app/views/handles/_search_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <a data-toggle="collapse" href="#collapse1">
      <h3 class="panel-title">
        Search
      </h3>
    </a>
  </div>
  <div id="collapse1" class="panel-collapse collapse <%= 'in' if @expand_sort_form %>">
    <div class="panel-body">
      <%= search_form_for @q do |f| %>
        <div class="row">
          <div class="col-md-6">
            <%= f.label :handle_cont %>
            <%= f.search_field :handle_cont, class: "form-control" %>
          </div>

          <div class="col-md-6">
            <%= f.label :url_cont %>
            <%= f.search_field :url_cont, class: "form-control" %>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6">
            <%= f.label :prefix_cont %>
            <%= f.search_field :prefix_cont, class: "form-control" %>
          </div>

          <div class="col-md-6">
            <%= f.label :suffix_eq %>
            <%= f.search_field :suffix_eq, class: "form-control" %>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6">
            <%= f.label :repo_cont %>
            <%= f.search_field :repo_cont, class: "form-control"%>
          </div>

          <div class="col-md-6">
            <%= f.label :repo_id_cont %>
            <%= f.search_field :repo_id_cont, class: "form-control"%>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6">
            <%= f.label :notes_cont %>
            <%= f.search_field :notes_cont, class: "form-control" %>
          </div>

          <div class="col-md-6">
            <%= f.label :description_cont %>
            <%= f.search_field :description_cont, class: "form-control" %>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12" style="margin-top: 10px">
            <%= f.submit class: 'btn btn-default' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/handles/edit.html.erb
<h1>Editing Handle</h1>

<%= render 'form', handle: @handle %>

app/views/handles/index.html.erb
<div class="page-header">
  <div class="row">
    <div class="col-xs-10">
      <span class="h1">Handles</span>
    </div>
    <div class="col-xs-2">
      <%= link_to 'New Handle', new_handle_path, class: 'btn btn-success pull-right' %>
    </div>
  </div>
</div>

<div>
  <%= render 'handles/search_form', q: @q %>
</div>

<% if @show_no_handles_found %>
  <%= render 'handles/no_handles_found' %>
<% else %>
  <div class="btn-toolbar">
    <div class="btn-group">
      <%= paginate @handles %>
    </div>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= sort_link(@q, :handle, [:handle, :prefix, :suffix]) %></th>
        <th><%= sort_link(@q, :url) %></th>
        <th><%= sort_link(@q, :repo) %></th>
        <th><%= sort_link(@q, :repo_id) %></th>
        <th><%= sort_link(@q, :updated_at, 'Last Update') %></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @handles.each do |handle| %>
        <tr>
          <td><%= link_to handle.to_handle_string, handle %></td>
          <td><%= link_to nil, handle.url %></td>
          <td><%= handle.repo %></td>
          <td><%= handle.repo_id %></td>
          <td title="<%= handle.updated_at.to_formatted_s %>"><%= time_ago_in_words(handle.updated_at) %> ago</td>
          <td>
            <span>
            <%= link_to 'Edit', edit_handle_path(handle), class: 'btn btn-info' %>
            <%= link_to 'Delete', handle, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            </span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @handles %>
<% end %>

app/views/handles/new.html.erb
<h1>New Handle</h1>

<%= render 'form', handle: @handle %>

app/views/handles/show.html.erb
<div class="page-heading">
  <h1><%= @handle.to_handle_string %> <small>Handle</small></h1>
</div>

<table class="table table-striped">
  <tbody>
  <tr>
    <th>Prefix</th>
    <td><%= @handle.prefix %></th>
  </tr>
  <tr>
    <th>Suffix</th>
    <td><%= @handle.suffix %></td>
  </tr>
  <tr>
    <th>Url</th>
    <td><%= link_to nil, @handle.url %></td>
  </tr>
  <tr>
    <th>Handle Url</th>
    <td><%= link_to nil, @handle.handle_url %></td>
  </tr>
  <tr>
    <th>Repository</th>
    <td><%= @handle.repo %></td>
  </tr>
  <tr>
    <th>Repository Id</th>
    <td><%= @handle.repo_id %></td>
  </tr>
  <tr>
    <th>Description</th>
    <td><%= @handle.description %></td>
  </tr>
  <tr>
    <th>Notes</th>
    <td><%= simple_format(@handle.notes.to_s) %></td>
  </tr>
  <tr>
    <th></th>
    <td>
      <%= link_to 'Edit', edit_handle_path(@handle), class: 'btn btn-info' %>
      <%= link_to 'List All Handles', handles_path, class: 'btn btn-default' %>
    </td>
  </tbody>
</table>